twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        denomination: '<h4 class="text-warning">Bijouterie de luxe</h4>'

    
when@test:
    twig:
        strict_variables: true
